imports:
    - { resource: parameters.ini }
    - { resource: security.yml }

framework:
    secret: %csrf_secret%
    charset:       UTF-8
    form: true
    csrf_protection: true
    router:        { resource: "%kernel.root_dir%/config/routing.yml" }
    validation:    { enable_annotations: true }
    templating:    { engines: ['twig'] } #assets_version: SomeVersionScheme
    session:
        default_locale: %locale%
        lifetime:       3600
        auto_start:     true

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%

# Doctrine Configuration
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8
    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%

fos_user:
    db_driver: orm
    firewall_name: main
    user_class: TSEP\Bundle\AdminBundle\Entity\User
